create table roles (id int8 generated by default as identity, role_name varchar(255), primary key (id));
create table tb_user_role (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
create table users (id int8 generated by default as identity, email varchar(255), name varchar(255), password varchar(255), primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists tb_user_role add constraint FK3ye7x0q4755dawlhrriknrckq foreign key (role_id) references roles;
alter table if exists tb_user_role add constraint FKnf85xeh20mwioj9m4mj1ibore foreign key (user_id) references users;
